const data = {
  products: [
    {
      _id: 1,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: 2,
      name: "Adidas Fit Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 90,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 89,
      description: "high quality product",
    },
    {
      _id: 3,
      name: "Lacoste Free Bag",
      category: "Bolsos",
      image: "/images/p3.jpg",
      price: 100,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      _id: 4,
      name: "Puma Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 80,
      brand: "Puma",
      rating: 4.5,
      numReviews: 12,
      description: "high quality product",
    },
    {
      _id: 5,
      name: "NB Xnew",
      category: "Shoes",
      image: "/images/p5.jpg",
      price: 160,
      brand: "New Balance",
      rating: 3.5,
      numReviews: 7,
      description: "high quality product",
    },
    {
      _id: 6,
      name: "RBZ x3",
      category: "Shoes",
      image: "/images/p6.jpg",
      price: 95,
      brand: "Reebook",
      rating: 5,
      numReviews: 100,
      description: "high quality product",
    },
  ],
};
export default data;
